In [ ]:
# Import library
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, classification_report, confusion_matrix
from google.colab import files

# **Step 1: Upload dan Load Data**
print("Unggah file data training Anda:")
uploaded = files.upload()
training_data = pd.read_csv(list(uploaded.keys())[0])

# **Step 2: Pisahkan fitur (X) dan label (y)**
X_train = training_data.drop(columns=["ID", "Status"])  # Sesuaikan nama kolom sesuai dataset
y_train = training_data["Status"]

# **Step 3: Model Training dengan Random Forest**
rf_model = RandomForestClassifier(random_state=42)
rf_model.fit(X_train, y_train)  # Latih model

# **Step 4: Sistem Prediksi**
print("\nSistem Prediksi Diabetes")
print("Masukkan nilai parameter sesuai dataset:")

# Ambil input dari pengguna untuk prediksi
user_input = []
for col in X_train.columns:
    value = float(input(f"Masukkan nilai untuk {col}: "))
    user_input.append(value)

# Prediksi berdasarkan input pengguna
user_data = np.array(user_input).reshape(1, -1)
user_prediction = rf_model.predict(user_data)

# Tampilkan hasil prediksi
categories = {1: "Normal", 2: "Prediabetes", 3: "Diabetes"}
print(f"Hasil Prediksi: {categories[user_prediction[0]]}")

# **Step 5: Evaluasi dengan Data Testing (Opsional, jika pengguna memiliki data testing)**
eval_choice = input("\nApakah Anda ingin mengevaluasi model dengan data testing? (ya/tidak): ").strip().lower()
if eval_choice == "ya":
    print("\nUnggah file data testing Anda:")
    uploaded = files.upload()
    testing_data = pd.read_csv(list(uploaded.keys())[0])

    # Pisahkan fitur dan label untuk data testing
    X_test = testing_data.drop(columns=["ID", "Status"])  # Sesuaikan nama kolom
    y_test = testing_data["Status"]

    # Evaluasi model pada data testing
    y_pred = rf_model.predict(X_test)
    y_proba = rf_model.predict_proba(X_test)

    # Metrik Evaluasi
    print("\nMetrik Evaluasi:")
    print(f"Accuracy: {accuracy_score(y_test, y_pred):.2f}")
    print(f"Precision: {precision_score(y_test, y_pred, average='weighted'):.2f}")
    print(f"Recall: {recall_score(y_test, y_pred, average='weighted'):.2f}")
    print(f"F1-Score: {f1_score(y_test, y_pred, average='weighted'):.2f}")

    # ROC-AUC untuk multiclass (One-vs-Rest)
    try:
        roc_auc = roc_auc_score(pd.get_dummies(y_test), y_proba, multi_class="ovr")
        print(f"ROC-AUC: {roc_auc:.2f}")
    except:
        print("ROC-AUC tidak valid untuk multiclass tanpa modifikasi.")

    # Classification Report dan Confusion Matrix
    print("\nClassification Report:\n", classification_report(y_test, y_pred))
    print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

print("\nProgram selesai. Terima kasih!")


Unggah file data training Anda:


Saving data_training.csv to data_training.csv

Sistem Prediksi Diabetes
Masukkan nilai parameter sesuai dataset:
Masukkan nilai untuk Age: 21
Masukkan nilai untuk Gender: 1
Masukkan nilai untuk BMI: 20
Masukkan nilai untuk SBP: 120
Masukkan nilai untuk U.GLU: 0
Masukkan nilai untuk PRO: 0
Masukkan nilai untuk TP: 77
Masukkan nilai untuk ALB: 50
Masukkan nilai untuk GLB: 30
Masukkan nilai untuk T.BIL: 20
Masukkan nilai untuk DB: 3
Masukkan nilai untuk IB: 9
Masukkan nilai untuk ALT: 20
Masukkan nilai untuk AST: 5
Masukkan nilai untuk BUN: 70
Masukkan nilai untuk SCr: 500
Masukkan nilai untuk UA: 5
Masukkan nilai untuk TC: 0.5
Masukkan nilai untuk TG: 1
Masukkan nilai untuk HDL.C: 3
Masukkan nilai untuk LDL.C: 1


/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


Hasil Prediksi: Normal

Apakah Anda ingin mengevaluasi model dengan data testing? (ya/tidak): ya

Unggah file data testing Anda:


Saving data_testing.csv to data_testing.csv

Metrik Evaluasi:
Accuracy: 0.71
Precision: 0.85
Recall: 0.71
F1-Score: 0.65
ROC-AUC: 0.96

Classification Report:
               precision    recall  f1-score   support

           1       1.00      1.00      1.00        44
           2       0.54      1.00      0.70        44
           3       1.00      0.14      0.24        44

    accuracy                           0.71       132
   macro avg       0.85      0.71      0.65       132
weighted avg       0.85      0.71      0.65       132


Confusion Matrix:
 [[44  0  0]
 [ 0 44  0]
 [ 0 38  6]]

Program selesai. Terima kasih!
